export const ITEMS = {
    10: {
        name: 'Pav Bhaji',
        description: 'a spicy curry of mixed vegetables (bhaji) cooked in a special blend of spices and served with soft bread pav shallow fried in butter.',
        price: '40',
        image: 'assets/pav-bhaji.jpg',
        avgPrepTime: '20 mins',
        availability: true,
        itemCategory: '',
        ratings: [],
    },
    11: {
        name: 'Pav Bhaji',
        description: 'a spicy curry of mixed vegetables (bhaji) cooked in a special blend of spices and served with soft bread pav shallow fried in butter.',
        price: '40',
        image: 'assets/pav-bhaji.jpg',
        avgPrepTime: '20 mins',
        availability: true,
        itemCategory: '',
        ratings: [],
    },
    12: {
        name: 'Pav Bhaji',
        description: 'a spicy curry of mixed vegetables (bhaji) cooked in a special blend of spices and served with soft bread pav shallow fried in butter.',
        price: '40',
        image: 'assets/pav-bhaji.jpg',
        avgPrepTime: '20 mins',
        availability: true,
        itemCategory: '',
        ratings: [],
    },
    13: {
        name: 'Pav Bhaji',
        description: 'a spicy curry of mixed vegetables (bhaji) cooked in a special blend of spices and served with soft bread pav shallow fried in butter.',
        price: '40',
        image: 'assets/pav-bhaji.jpg',
        avgPrepTime: '20 mins',
        availability: true,
        itemCategory: '',
        ratings: [],
    },
    14: {
        name: 'Pav Bhaji',
        description: 'a spicy curry of mixed vegetables (bhaji) cooked in a special blend of spices and served with soft bread pav shallow fried in butter.',
        price: '40',
        image: 'assets/pav-bhaji.jpg',
        avgPrepTime: '20 mins',
        availability: true,
        itemCategory: '',
        ratings: [],
    },
    15: {
        name: 'Pav Bhaji',
        description: 'a spicy curry of mixed vegetables (bhaji) cooked in a special blend of spices and served with soft bread pav shallow fried in butter.',
        price: '40',
        image: 'assets/pav-bhaji.jpg',
        avgPrepTime: '20 mins',
        availability: true,
        itemCategory: '',
        ratings: [],
    },
    16: {
        name: 'Pav Bhaji',
        description: 'a spicy curry of mixed vegetables (bhaji) cooked in a special blend of spices and served with soft bread pav shallow fried in butter.',
        price: '40',
        image: 'assets/pav-bhaji.jpg',
        avgPrepTime: '20 mins',
        availability: true,
        itemCategory: '',
        ratings: [],
    },
    17: {
        name: 'Pav Bhaji',
        description: 'a spicy curry of mixed vegetables (bhaji) cooked in a special blend of spices and served with soft bread pav shallow fried in butter.',
        price: '40',
        image: 'assets/pav-bhaji.jpg',
        avgPrepTime: '20 mins',
        availability: true,
        itemCategory: '',
        ratings: [],
    },
    18: {
        name: 'Pav Bhaji',
        description: 'a spicy curry of mixed vegetables (bhaji) cooked in a special blend of spices and served with soft bread pav shallow fried in butter.',
        price: '40',
        image: 'assets/pav-bhaji.jpg',
        avgPrepTime: '20 mins',
        availability: true,
        itemCategory: '',
        ratings: [],
    },
    19: {
        name: 'Pav Bhaji',
        description: 'a spicy curry of mixed vegetables (bhaji) cooked in a special blend of spices and served with soft bread pav shallow fried in butter.',
        price: '40',
        image: 'assets/pav-bhaji.jpg',
        avgPrepTime: '20 mins',
        availability: true,
        itemCategory: '',
        ratings: [],
    },
    20: {
        name: 'Pav Bhaji',
        description: 'a spicy curry of mixed vegetables (bhaji) cooked in a special blend of spices and served with soft bread pav shallow fried in butter.',
        price: '40',
        image: 'assets/pav-bhaji.jpg',
        avgPrepTime: '20 mins',
        availability: true,
        itemCategory: '',
        ratings: [],
    },
    21: {
        name: 'Pav Bhaji',
        description: 'a spicy curry of mixed vegetables (bhaji) cooked in a special blend of spices and served with soft bread pav shallow fried in butter.',
        price: '40',
        image: 'assets/pav-bhaji.jpg',
        avgPrepTime: '20 mins',
        availability: true,
        itemCategory: '',
        ratings: [],
    },
}