export const ITEMS = {
    5001: {
        name: 'Pav Bhaji',
        description: 'a spicy curry of mixed vegetables (bhaji) cooked in a special blend of spices and served with soft bread pav shallow fried in butter.',
        price: '40',
        image: 'assets/pav-bhaji.jpg',
        avgPrepTime: '20 mins',
        availability: true,
        itemCategory: '',
        ratings: [],
    },
    5002: {
        name: 'Pav Bhaji',
        description: 'a spicy curry of mixed vegetables (bhaji) cooked in a special blend of spices and served with soft bread pav shallow fried in butter.',
        price: '40',
        image: 'assets/pav-bhaji.jpg',
        avgPrepTime: '20 mins',
        availability: true,
        itemCategory: '',
        ratings: [],
    },
    5003: {
        name: 'Pav Bhaji',
        description: 'a spicy curry of mixed vegetables (bhaji) cooked in a special blend of spices and served with soft bread pav shallow fried in butter.',
        price: '40',
        image: 'assets/pav-bhaji.jpg',
        avgPrepTime: '20 mins',
        availability: true,
        itemCategory: '',
        ratings: [],
    },
    5004: {
        name: 'Pav Bhaji',
        description: 'a spicy curry of mixed vegetables (bhaji) cooked in a special blend of spices and served with soft bread pav shallow fried in butter.',
        price: '40',
        image: 'assets/pav-bhaji.jpg',
        avgPrepTime: '20 mins',
        availability: true,
        itemCategory: '',
        ratings: [],
    },
    5005: {
        name: 'Pav Bhaji',
        description: 'a spicy curry of mixed vegetables (bhaji) cooked in a special blend of spices and served with soft bread pav shallow fried in butter.',
        price: '40',
        image: 'assets/pav-bhaji.jpg',
        avgPrepTime: '20 mins',
        availability: true,
        itemCategory: '',
        ratings: [],
    },
    5006: {
        name: 'Pav Bhaji',
        description: 'a spicy curry of mixed vegetables (bhaji) cooked in a special blend of spices and served with soft bread pav shallow fried in butter.',
        price: '40',
        image: 'assets/pav-bhaji.jpg',
        avgPrepTime: '20 mins',
        availability: true,
        itemCategory: '',
        ratings: [],
    },
    5007: {
        name: 'Pav Bhaji',
        description: 'a spicy curry of mixed vegetables (bhaji) cooked in a special blend of spices and served with soft bread pav shallow fried in butter.',
        price: '40',
        image: 'assets/pav-bhaji.jpg',
        avgPrepTime: '20 mins',
        availability: true,
        itemCategory: '',
        ratings: [],
    },
    5008: {
        name: 'Pav Bhaji',
        description: 'a spicy curry of mixed vegetables (bhaji) cooked in a special blend of spices and served with soft bread pav shallow fried in butter.',
        price: '40',
        image: 'assets/pav-bhaji.jpg',
        avgPrepTime: '20 mins',
        availability: true,
        itemCategory: '',
        ratings: [],
    },
    5009: {
        name: 'Pav Bhaji',
        description: 'a spicy curry of mixed vegetables (bhaji) cooked in a special blend of spices and served with soft bread pav shallow fried in butter.',
        price: '40',
        image: 'assets/pav-bhaji.jpg',
        avgPrepTime: '20 mins',
        availability: true,
        itemCategory: '',
        ratings: [],
    },
    5010: {
        name: 'Pav Bhaji',
        description: 'a spicy curry of mixed vegetables (bhaji) cooked in a special blend of spices and served with soft bread pav shallow fried in butter.',
        price: '40',
        image: 'assets/pav-bhaji.jpg',
        avgPrepTime: '20 mins',
        availability: true,
        itemCategory: '',
        ratings: [],
    },
    5011: {
        name: 'Pav Bhaji',
        description: 'a spicy curry of mixed vegetables (bhaji) cooked in a special blend of spices and served with soft bread pav shallow fried in butter.',
        price: '40',
        image: 'assets/pav-bhaji.jpg',
        avgPrepTime: '20 mins',
        availability: true,
        itemCategory: '',
        ratings: [],
    },
    5012: {
        name: 'Pav Bhaji',
        description: 'a spicy curry of mixed vegetables (bhaji) cooked in a special blend of spices and served with soft bread pav shallow fried in butter.',
        price: '40',
        image: 'assets/pav-bhaji.jpg',
        avgPrepTime: '20 mins',
        availability: true,
        itemCategory: '',
        ratings: [],
    },
}