export const USERS = {
    1000: {
        id: 1000,
        role: 'vendor',
        name: 'Surjeet',
        username: 'surjeet',
        email: 'surjeet@iongroup.com',
        password: 'surjeet_pwd',
        prefferedNumber: 9090887761
    },
    1001: {
        id: 1001,
        role: 'customer',
        name: 'Shantnu',
        username: 'shantnu',
        email: 'shantnu@iongroup.com',
        password: 'shantnu_pwd',
        prefferedNumber: 9090887762,
    },
    1002: {
        id: 1002,
        role: 'customer',
        name: 'Kashif',
        username: 'kashif',
        email: 'kashif@iongroup.com',
        password: 'kashif_pwd',
        prefferedNumber: 9090887763,
    },
    1003: {
        id: 1003,
        role: 'customer',
        name: 'Devanshu',
        username: 'devanshu',
        email: 'devanshu@iongroup.com',
        password: 'devanshu_pwd',
        prefferedNumber: 9090887764,
    },
    1004: {
        id: 1004,
        role: 'customer',
        name: 'Neha',
        username: 'neha',
        email: 'neha@iongroup.com',
        password: 'neha_pwd',
        prefferedNumber: 9090887764,
    },
};